// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/optimizer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectionType int32

const (
	SelectionType_SELECTION_UNSPECIFIED SelectionType = 0
	SelectionType_SELECTION_TOURNAMENT  SelectionType = 1 // Турнирная
	SelectionType_SELECTION_ROULETTE    SelectionType = 2 // Рулетка
	SelectionType_SELECTION_RANK        SelectionType = 3 // Ранговая
)

// Enum value maps for SelectionType.
var (
	SelectionType_name = map[int32]string{
		0: "SELECTION_UNSPECIFIED",
		1: "SELECTION_TOURNAMENT",
		2: "SELECTION_ROULETTE",
		3: "SELECTION_RANK",
	}
	SelectionType_value = map[string]int32{
		"SELECTION_UNSPECIFIED": 0,
		"SELECTION_TOURNAMENT":  1,
		"SELECTION_ROULETTE":    2,
		"SELECTION_RANK":        3,
	}
)

func (x SelectionType) Enum() *SelectionType {
	p := new(SelectionType)
	*p = x
	return p
}

func (x SelectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SelectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_optimizer_proto_enumTypes[0].Descriptor()
}

func (SelectionType) Type() protoreflect.EnumType {
	return &file_api_proto_optimizer_proto_enumTypes[0]
}

func (x SelectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SelectionType.Descriptor instead.
func (SelectionType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_optimizer_proto_rawDescGZIP(), []int{0}
}

type CrossoverType int32

const (
	CrossoverType_CROSSOVER_UNSPECIFIED  CrossoverType = 0
	CrossoverType_CROSSOVER_UNIFORM      CrossoverType = 1 // Равномерный
	CrossoverType_CROSSOVER_SINGLE_POINT CrossoverType = 2 // Одноточечный
	CrossoverType_CROSSOVER_TWO_POINT    CrossoverType = 3 // Двухточечный
)

// Enum value maps for CrossoverType.
var (
	CrossoverType_name = map[int32]string{
		0: "CROSSOVER_UNSPECIFIED",
		1: "CROSSOVER_UNIFORM",
		2: "CROSSOVER_SINGLE_POINT",
		3: "CROSSOVER_TWO_POINT",
	}
	CrossoverType_value = map[string]int32{
		"CROSSOVER_UNSPECIFIED":  0,
		"CROSSOVER_UNIFORM":      1,
		"CROSSOVER_SINGLE_POINT": 2,
		"CROSSOVER_TWO_POINT":    3,
	}
)

func (x CrossoverType) Enum() *CrossoverType {
	p := new(CrossoverType)
	*p = x
	return p
}

func (x CrossoverType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrossoverType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_optimizer_proto_enumTypes[1].Descriptor()
}

func (CrossoverType) Type() protoreflect.EnumType {
	return &file_api_proto_optimizer_proto_enumTypes[1]
}

func (x CrossoverType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrossoverType.Descriptor instead.
func (CrossoverType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_optimizer_proto_rawDescGZIP(), []int{1}
}

type MutationType int32

const (
	MutationType_MUTATION_UNSPECIFIED MutationType = 0
	MutationType_MUTATION_INVERSION   MutationType = 1 // Инверсивная
	MutationType_MUTATION_SWAP        MutationType = 2 // Перестановка
)

// Enum value maps for MutationType.
var (
	MutationType_name = map[int32]string{
		0: "MUTATION_UNSPECIFIED",
		1: "MUTATION_INVERSION",
		2: "MUTATION_SWAP",
	}
	MutationType_value = map[string]int32{
		"MUTATION_UNSPECIFIED": 0,
		"MUTATION_INVERSION":   1,
		"MUTATION_SWAP":        2,
	}
)

func (x MutationType) Enum() *MutationType {
	p := new(MutationType)
	*p = x
	return p
}

func (x MutationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_optimizer_proto_enumTypes[2].Descriptor()
}

func (MutationType) Type() protoreflect.EnumType {
	return &file_api_proto_optimizer_proto_enumTypes[2]
}

func (x MutationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationType.Descriptor instead.
func (MutationType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_optimizer_proto_rawDescGZIP(), []int{2}
}

type TransportType int32

const (
	TransportType_TRANSPORT_UNSPECIFIED TransportType = 0
	TransportType_TRANSPORT_1_5T_10M3   TransportType = 1 // 1.5т / 10м3
	TransportType_TRANSPORT_3T_20M3     TransportType = 2 // 3т / 20м3
	TransportType_TRANSPORT_5T_36M3     TransportType = 3 // 5т / 36м3
	TransportType_TRANSPORT_10T_45M3    TransportType = 4 // 10т / 45м3
	TransportType_TRANSPORT_20T_86M3    TransportType = 5 // 20т / 86м3
)

// Enum value maps for TransportType.
var (
	TransportType_name = map[int32]string{
		0: "TRANSPORT_UNSPECIFIED",
		1: "TRANSPORT_1_5T_10M3",
		2: "TRANSPORT_3T_20M3",
		3: "TRANSPORT_5T_36M3",
		4: "TRANSPORT_10T_45M3",
		5: "TRANSPORT_20T_86M3",
	}
	TransportType_value = map[string]int32{
		"TRANSPORT_UNSPECIFIED": 0,
		"TRANSPORT_1_5T_10M3":   1,
		"TRANSPORT_3T_20M3":     2,
		"TRANSPORT_5T_36M3":     3,
		"TRANSPORT_10T_45M3":    4,
		"TRANSPORT_20T_86M3":    5,
	}
)

func (x TransportType) Enum() *TransportType {
	p := new(TransportType)
	*p = x
	return p
}

func (x TransportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_optimizer_proto_enumTypes[3].Descriptor()
}

func (TransportType) Type() protoreflect.EnumType {
	return &file_api_proto_optimizer_proto_enumTypes[3]
}

func (x TransportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportType.Descriptor instead.
func (TransportType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_optimizer_proto_rawDescGZIP(), []int{3}
}

type OptimizeRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Direction string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"` // Направление: "Восток", "Северо-Запад", "Юг", "Волга"
	// Параметры ГА для 1-го уровня (выбор терминалов)
	GaSettingsLevel_1 *GASettings `protobuf:"bytes,2,opt,name=ga_settings_level_1,json=gaSettingsLevel1,proto3" json:"ga_settings_level_1,omitempty"`
	// Дни отгрузки (ровно 2)
	DeliveryDays  []string `protobuf:"bytes,3,rep,name=delivery_days,json=deliveryDays,proto3" json:"delivery_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	mi := &file_api_proto_optimizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_optimizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_optimizer_proto_rawDescGZIP(), []int{0}
}

func (x *OptimizeRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *OptimizeRequest) GetGaSettingsLevel_1() *GASettings {
	if x != nil {
		return x.GaSettingsLevel_1
	}
	return nil
}

func (x *OptimizeRequest) GetDeliveryDays() []string {
	if x != nil {
		return x.DeliveryDays
	}
	return nil
}

type GASettings struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NumGenerations    int32                  `protobuf:"varint,1,opt,name=num_generations,json=numGenerations,proto3" json:"num_generations,omitempty"`                            // Количество поколений
	NumIndividuals    int32                  `protobuf:"varint,2,opt,name=num_individuals,json=numIndividuals,proto3" json:"num_individuals,omitempty"`                            // Количество индивидов (размер популяции)
	SelectionType     SelectionType          `protobuf:"varint,3,opt,name=selection_type,json=selectionType,proto3,enum=noytech.v1.SelectionType" json:"selection_type,omitempty"` // Тип селекции
	CrossoverType     CrossoverType          `protobuf:"varint,4,opt,name=crossover_type,json=crossoverType,proto3,enum=noytech.v1.CrossoverType" json:"crossover_type,omitempty"` // Тип скрещивания
	MutationType      MutationType           `protobuf:"varint,5,opt,name=mutation_type,json=mutationType,proto3,enum=noytech.v1.MutationType" json:"mutation_type,omitempty"`     // Тип мутации
	StoppingCriterion int32                  `protobuf:"varint,6,opt,name=stopping_criterion,json=stoppingCriterion,proto3" json:"stopping_criterion,omitempty"`                   // Критерий остановки
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GASettings) Reset() {
	*x = GASettings{}
	mi := &file_api_proto_optimizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GASettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GASettings) ProtoMessage() {}

func (x *GASettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_optimizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GASettings.ProtoReflect.Descriptor instead.
func (*GASettings) Descriptor() ([]byte, []int) {
	return file_api_proto_optimizer_proto_rawDescGZIP(), []int{1}
}

func (x *GASettings) GetNumGenerations() int32 {
	if x != nil {
		return x.NumGenerations
	}
	return 0
}

func (x *GASettings) GetNumIndividuals() int32 {
	if x != nil {
		return x.NumIndividuals
	}
	return 0
}

func (x *GASettings) GetSelectionType() SelectionType {
	if x != nil {
		return x.SelectionType
	}
	return SelectionType_SELECTION_UNSPECIFIED
}

func (x *GASettings) GetCrossoverType() CrossoverType {
	if x != nil {
		return x.CrossoverType
	}
	return CrossoverType_CROSSOVER_UNSPECIFIED
}

func (x *GASettings) GetMutationType() MutationType {
	if x != nil {
		return x.MutationType
	}
	return MutationType_MUTATION_UNSPECIFIED
}

func (x *GASettings) GetStoppingCriterion() int32 {
	if x != nil {
		return x.StoppingCriterion
	}
	return 0
}

type OptimizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Results       []*OptimizationResult  `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	SolutionId    string                 `protobuf:"bytes,4,opt,name=solution_id,json=solutionId,proto3" json:"solution_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeResponse) Reset() {
	*x = OptimizeResponse{}
	mi := &file_api_proto_optimizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeResponse) ProtoMessage() {}

func (x *OptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_optimizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeResponse.ProtoReflect.Descriptor instead.
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_optimizer_proto_rawDescGZIP(), []int{2}
}

func (x *OptimizeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OptimizeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OptimizeResponse) GetResults() []*OptimizationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *OptimizeResponse) GetSolutionId() string {
	if x != nil {
		return x.SolutionId
	}
	return ""
}

func (x *OptimizeResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type OptimizationResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Routes          []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`                                          // Маршруты (линейхолы)
	Cost            *CostBreakdown         `protobuf:"bytes,2,opt,name=cost,proto3" json:"cost,omitempty"`                                              // Общая стоимость
	ActiveTerminals []string               `protobuf:"bytes,3,rep,name=active_terminals,json=activeTerminals,proto3" json:"active_terminals,omitempty"` // Активные терминалы (города)
	Generation      int32                  `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`                                 // Поколение, на котором найдено решение
	FitnessScore    float64                `protobuf:"fixed64,5,opt,name=fitness_score,json=fitnessScore,proto3" json:"fitness_score,omitempty"`        // Значение функции пригодности (целевая функция)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OptimizationResult) Reset() {
	*x = OptimizationResult{}
	mi := &file_api_proto_optimizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizationResult) ProtoMessage() {}

func (x *OptimizationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_optimizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizationResult.ProtoReflect.Descriptor instead.
func (*OptimizationResult) Descriptor() ([]byte, []int) {
	return file_api_proto_optimizer_proto_rawDescGZIP(), []int{3}
}

func (x *OptimizationResult) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *OptimizationResult) GetCost() *CostBreakdown {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *OptimizationResult) GetActiveTerminals() []string {
	if x != nil {
		return x.ActiveTerminals
	}
	return nil
}

func (x *OptimizationResult) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *OptimizationResult) GetFitnessScore() float64 {
	if x != nil {
		return x.FitnessScore
	}
	return 0
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCity      string                 `protobuf:"bytes,1,opt,name=from_city,json=fromCity,proto3" json:"from_city,omitempty"`                                               // Москва
	ToTerminal    string                 `protobuf:"bytes,2,opt,name=to_terminal,json=toTerminal,proto3" json:"to_terminal,omitempty"`                                         // Терминал (город)
	ShipmentIds   []string               `protobuf:"bytes,3,rep,name=shipment_ids,json=shipmentIds,proto3" json:"shipment_ids,omitempty"`                                      // ID грузов, назначенных на этот маршрут
	Cost          float64                `protobuf:"fixed64,4,opt,name=cost,proto3" json:"cost,omitempty"`                                                                     // Стоимость этого лайнхола
	TransportUsed TransportType          `protobuf:"varint,5,opt,name=transport_used,json=transportUsed,proto3,enum=noytech.v1.TransportType" json:"transport_used,omitempty"` // Использованный тип ТС
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_api_proto_optimizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_optimizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_api_proto_optimizer_proto_rawDescGZIP(), []int{4}
}

func (x *Route) GetFromCity() string {
	if x != nil {
		return x.FromCity
	}
	return ""
}

func (x *Route) GetToTerminal() string {
	if x != nil {
		return x.ToTerminal
	}
	return ""
}

func (x *Route) GetShipmentIds() []string {
	if x != nil {
		return x.ShipmentIds
	}
	return nil
}

func (x *Route) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Route) GetTransportUsed() TransportType {
	if x != nil {
		return x.TransportUsed
	}
	return TransportType_TRANSPORT_UNSPECIFIED
}

type CostBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinehaulCost  float64                `protobuf:"fixed64,1,opt,name=linehaul_cost,json=linehaulCost,proto3" json:"linehaul_cost,omitempty"`   // Стоимость лайнхолов
	LastMileCost  float64                `protobuf:"fixed64,2,opt,name=last_mile_cost,json=lastMileCost,proto3" json:"last_mile_cost,omitempty"` // Стоимость последней мили
	PenaltyCost   float64                `protobuf:"fixed64,3,opt,name=penalty_cost,json=penaltyCost,proto3" json:"penalty_cost,omitempty"`      // Штрафы
	TotalCost     float64                `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`            // Общая стоимость
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostBreakdown) Reset() {
	*x = CostBreakdown{}
	mi := &file_api_proto_optimizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostBreakdown) ProtoMessage() {}

func (x *CostBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_optimizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostBreakdown.ProtoReflect.Descriptor instead.
func (*CostBreakdown) Descriptor() ([]byte, []int) {
	return file_api_proto_optimizer_proto_rawDescGZIP(), []int{5}
}

func (x *CostBreakdown) GetLinehaulCost() float64 {
	if x != nil {
		return x.LinehaulCost
	}
	return 0
}

func (x *CostBreakdown) GetLastMileCost() float64 {
	if x != nil {
		return x.LastMileCost
	}
	return 0
}

func (x *CostBreakdown) GetPenaltyCost() float64 {
	if x != nil {
		return x.PenaltyCost
	}
	return 0
}

func (x *CostBreakdown) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

var File_api_proto_optimizer_proto protoreflect.FileDescriptor

const file_api_proto_optimizer_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/optimizer.proto\x12\n" +
	"noytech.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n" +
	"\x0fOptimizeRequest\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12E\n" +
	"\x13ga_settings_level_1\x18\x02 \x01(\v2\x16.noytech.v1.GASettingsR\x10gaSettingsLevel1\x12#\n" +
	"\rdelivery_days\x18\x03 \x03(\tR\fdeliveryDays\"\xd0\x02\n" +
	"\n" +
	"GASettings\x12'\n" +
	"\x0fnum_generations\x18\x01 \x01(\x05R\x0enumGenerations\x12'\n" +
	"\x0fnum_individuals\x18\x02 \x01(\x05R\x0enumIndividuals\x12@\n" +
	"\x0eselection_type\x18\x03 \x01(\x0e2\x19.noytech.v1.SelectionTypeR\rselectionType\x12@\n" +
	"\x0ecrossover_type\x18\x04 \x01(\x0e2\x19.noytech.v1.CrossoverTypeR\rcrossoverType\x12=\n" +
	"\rmutation_type\x18\x05 \x01(\x0e2\x18.noytech.v1.MutationTypeR\fmutationType\x12-\n" +
	"\x12stopping_criterion\x18\x06 \x01(\x05R\x11stoppingCriterion\"\xdc\x01\n" +
	"\x10OptimizeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\aresults\x18\x03 \x03(\v2\x1e.noytech.v1.OptimizationResultR\aresults\x12\x1f\n" +
	"\vsolution_id\x18\x04 \x01(\tR\n" +
	"solutionId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xde\x01\n" +
	"\x12OptimizationResult\x12)\n" +
	"\x06routes\x18\x01 \x03(\v2\x11.noytech.v1.RouteR\x06routes\x12-\n" +
	"\x04cost\x18\x02 \x01(\v2\x19.noytech.v1.CostBreakdownR\x04cost\x12)\n" +
	"\x10active_terminals\x18\x03 \x03(\tR\x0factiveTerminals\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x05R\n" +
	"generation\x12#\n" +
	"\rfitness_score\x18\x05 \x01(\x01R\ffitnessScore\"\xbe\x01\n" +
	"\x05Route\x12\x1b\n" +
	"\tfrom_city\x18\x01 \x01(\tR\bfromCity\x12\x1f\n" +
	"\vto_terminal\x18\x02 \x01(\tR\n" +
	"toTerminal\x12!\n" +
	"\fshipment_ids\x18\x03 \x03(\tR\vshipmentIds\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x01R\x04cost\x12@\n" +
	"\x0etransport_used\x18\x05 \x01(\x0e2\x19.noytech.v1.TransportTypeR\rtransportUsed\"\x9c\x01\n" +
	"\rCostBreakdown\x12#\n" +
	"\rlinehaul_cost\x18\x01 \x01(\x01R\flinehaulCost\x12$\n" +
	"\x0elast_mile_cost\x18\x02 \x01(\x01R\flastMileCost\x12!\n" +
	"\fpenalty_cost\x18\x03 \x01(\x01R\vpenaltyCost\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x04 \x01(\x01R\ttotalCost*p\n" +
	"\rSelectionType\x12\x19\n" +
	"\x15SELECTION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SELECTION_TOURNAMENT\x10\x01\x12\x16\n" +
	"\x12SELECTION_ROULETTE\x10\x02\x12\x12\n" +
	"\x0eSELECTION_RANK\x10\x03*v\n" +
	"\rCrossoverType\x12\x19\n" +
	"\x15CROSSOVER_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CROSSOVER_UNIFORM\x10\x01\x12\x1a\n" +
	"\x16CROSSOVER_SINGLE_POINT\x10\x02\x12\x17\n" +
	"\x13CROSSOVER_TWO_POINT\x10\x03*S\n" +
	"\fMutationType\x12\x18\n" +
	"\x14MUTATION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MUTATION_INVERSION\x10\x01\x12\x11\n" +
	"\rMUTATION_SWAP\x10\x02*\xa1\x01\n" +
	"\rTransportType\x12\x19\n" +
	"\x15TRANSPORT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TRANSPORT_1_5T_10M3\x10\x01\x12\x15\n" +
	"\x11TRANSPORT_3T_20M3\x10\x02\x12\x15\n" +
	"\x11TRANSPORT_5T_36M3\x10\x03\x12\x16\n" +
	"\x12TRANSPORT_10T_45M3\x10\x04\x12\x16\n" +
	"\x12TRANSPORT_20T_86M3\x10\x052Y\n" +
	"\x10OptimizerService\x12E\n" +
	"\bOptimize\x12\x1b.noytech.v1.OptimizeRequest\x1a\x1c.noytech.v1.OptimizeResponseB Z\x1enoytech-ga-optimizer/api/protob\x06proto3"

var (
	file_api_proto_optimizer_proto_rawDescOnce sync.Once
	file_api_proto_optimizer_proto_rawDescData []byte
)

func file_api_proto_optimizer_proto_rawDescGZIP() []byte {
	file_api_proto_optimizer_proto_rawDescOnce.Do(func() {
		file_api_proto_optimizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_optimizer_proto_rawDesc), len(file_api_proto_optimizer_proto_rawDesc)))
	})
	return file_api_proto_optimizer_proto_rawDescData
}

var file_api_proto_optimizer_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_proto_optimizer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_optimizer_proto_goTypes = []any{
	(SelectionType)(0),            // 0: noytech.v1.SelectionType
	(CrossoverType)(0),            // 1: noytech.v1.CrossoverType
	(MutationType)(0),             // 2: noytech.v1.MutationType
	(TransportType)(0),            // 3: noytech.v1.TransportType
	(*OptimizeRequest)(nil),       // 4: noytech.v1.OptimizeRequest
	(*GASettings)(nil),            // 5: noytech.v1.GASettings
	(*OptimizeResponse)(nil),      // 6: noytech.v1.OptimizeResponse
	(*OptimizationResult)(nil),    // 7: noytech.v1.OptimizationResult
	(*Route)(nil),                 // 8: noytech.v1.Route
	(*CostBreakdown)(nil),         // 9: noytech.v1.CostBreakdown
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_api_proto_optimizer_proto_depIdxs = []int32{
	5,  // 0: noytech.v1.OptimizeRequest.ga_settings_level_1:type_name -> noytech.v1.GASettings
	0,  // 1: noytech.v1.GASettings.selection_type:type_name -> noytech.v1.SelectionType
	1,  // 2: noytech.v1.GASettings.crossover_type:type_name -> noytech.v1.CrossoverType
	2,  // 3: noytech.v1.GASettings.mutation_type:type_name -> noytech.v1.MutationType
	7,  // 4: noytech.v1.OptimizeResponse.results:type_name -> noytech.v1.OptimizationResult
	10, // 5: noytech.v1.OptimizeResponse.created_at:type_name -> google.protobuf.Timestamp
	8,  // 6: noytech.v1.OptimizationResult.routes:type_name -> noytech.v1.Route
	9,  // 7: noytech.v1.OptimizationResult.cost:type_name -> noytech.v1.CostBreakdown
	3,  // 8: noytech.v1.Route.transport_used:type_name -> noytech.v1.TransportType
	4,  // 9: noytech.v1.OptimizerService.Optimize:input_type -> noytech.v1.OptimizeRequest
	6,  // 10: noytech.v1.OptimizerService.Optimize:output_type -> noytech.v1.OptimizeResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_optimizer_proto_init() }
func file_api_proto_optimizer_proto_init() {
	if File_api_proto_optimizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_optimizer_proto_rawDesc), len(file_api_proto_optimizer_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_optimizer_proto_goTypes,
		DependencyIndexes: file_api_proto_optimizer_proto_depIdxs,
		EnumInfos:         file_api_proto_optimizer_proto_enumTypes,
		MessageInfos:      file_api_proto_optimizer_proto_msgTypes,
	}.Build()
	File_api_proto_optimizer_proto = out.File
	file_api_proto_optimizer_proto_goTypes = nil
	file_api_proto_optimizer_proto_depIdxs = nil
}
